version: 2.1

jobs:
  test:
    parameters:
      ruby:
        type: string
    docker:
      - image: 'cimg/ruby:<< parameters.ruby >>'
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec
      - run: bundle exec standardrb

workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby: ["3.2", "3.1", "3.0", "2.7", "2.6"]
