ruby: &ruby
  image: carwow/ruby-ci:2.6

version: 2

jobs:
  tests:
    docker:
      - *ruby
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-
      - run: |
          bundle config --local path vendor/bundle &&
          bundle check || bundle install --jobs=4 --retry=3
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: [~/honeykiq/vendor/bundle]
      - run: bundle exec rubocop
      - run: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - tests
